### ISSUE TITLE
Sajat adatok szerkesztese

### ISSUE THREAD

**Issue by emanreyalp** [os-bme/hotstock#12]
Sima User jogosultsaggal a sajat adatokat lehessen szerkeszteni

**Comment by veresspeter** [comment]
A master és a filehandle-ing branch-en is működik az adatok szerkesztése.
Jobb felső sarok saját név mellett lenyiló menü, "my profile", majd a megjelenő oldalon "edit datas"-ra kattintva a megjelenő kártyán lehet szerkeszti az adatokat, a név és neptunkód kivételével. Ezek csak SuperAdmin által szerkeszthetőek.
